[tool.poetry]
name = "text-anomalies"
version = "0.1.0"
description = ""
authors = ["Sebastian Mohr <sebastian@mohrenclan.de>"]
readme = "README.md"
packages = [{ include = "text_anomalies" }]

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.13.0"
torchdata = "^0.5.0"
torchtext = "^0.14.0"
ipython = "^8.6.0"
ipykernel = "^6.17.0"
pandas = "^1.5.1"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
